[package]
name = "share_lib"
version = "0.1.0"
authors = ["afedoseev <afedoseev@AFEDOSEEV>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.6"
crc = {git = "https://github.com/mrhooray/crc-rs.git"}
